env: zayas

env_args:
  struct_type: "zayas"
  n_comp: 22
  freq_col: [5.e-1, 5.e-2, 1.e-2, 5.e-4, 5.e-5]
  discount_reward: 0.95
  state_obs: True
  state_d_rate: True
  obs_d_rate: True
  obs_multiple: False
  obs_all_d_rate: False
  campaign_cost: False

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
test_interval: 10000
test_nepisode: 100
test_greedy: True
t_max: 2050000
